### ISSUE TITLE
Okta URL Generation

### ISSUE THREAD

**Issue by devilwacause** [manywho/service-okta#25]
Okta fails to allow authentication because the URL generated by Boomi Flow includes two (2) redirect_uri 's.

Brought this up during a Boomi Flow training but was not taken seriously.

Removing one of the redirect_uri's from the URL generated by Flow - allows Okta to continue with authentication and redirects correctly back to the Flow that initiated the request.

Attached info

**Boomi Flow URL**
https://flow.manywho.com/a0f0e1b8-4924-451e-b3df-01a7fcc33c8d/play/default?flow-id=b204fbbb-ec9f-44e4-ac72-782733e24ab8&flow-version-id=eb68ec54-73fd-45e6-987c-7855612a89d5

**URL sent to Okta**
https://**redacted**.okta.com/oauth2/v1/authorize?response_type=code&client_id=**redacted**&redirect_uri=https%3A%2F%2Fflow.manywho.com%2Fapi%2Frun%2F1%2Foauth2&scope=openid%20email%20profile&state=StateId____4289c5b4-5f0d-4409-9c77-59f62dca738f____StateIdTenantId____a0f0e1b8-4924-451e-b3df-01a7fcc33c8d____TenantIdToken____NONE____TokenServiceElementId____875210da-d299-43fb-9843-b9eddc25a049____ServiceElementIdIsInitialization____true____IsInitialization&redirect_uri=https%3A%2F%2Fflow.manywho.com%2Fapi%2Frun%2F1%2Foauth2

**Error Response In URI**
https://flow.manywho.com/api/run/1/oauth2?state=StateId____4289c5b4-5f0d-4409-9c77-59f62dca738f____StateIdTenantId____a0f0e1b8-4924-451e-b3df-01a7fcc33c8d____TenantIdToken____NONE____TokenServiceElementId____875210da-d299-43fb-9843-b9eddc25a049____ServiceElementIdIsInitialization____true____IsInitialization&error=invalid_request&error_description=Duplicate+parameter+provided+in+request.+Duplicated+parameters%3A+%5Bredirect_uri%5D.

**Error Response As Seen in Browser** 
![image](https://user-images.githubusercontent.com/24920886/123685900-cc17f600-d814-11eb-9ae2-4033728b6cbe.png)
![image](https://user-images.githubusercontent.com/24920886/123685920-d2a66d80-d814-11eb-9c94-0e07e05fdc8a.png)

**Comment by williamjeccles** [comment]
Hello, 

We plan to address this in a future update to Flow but in the meantime here is a documented solution to the duplication issue.

To fully support the idea of refresh tokens and keeping the users session alive for as long as the identity provider can, which can be upto 30 days. The following needs to be added to a custom player, just before the call to manywho.engine.initialize

```
function getCookie(name) {
    var nameEQ = name + "=";
    var ca = document.cookie.split(';');
    for(var i=0;i < ca.length;i++) {
        var c = ca[i];
        while (c.charAt(0)==' ') c = c.substring(1,c.length);
        if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length,c.length);
    }
    return null;
}

manywho.state.setAuthenticationToken = function(token, flowKey) {
    var tenantId = manywho.utils.extractTenantId(flowKey);
    document.cookie = tenantId + '=' + (token ? token : '') + '; max-age=' + (60 * 60).toString();
}

manywho.state.getAuthenticationToken = function(flowKey) {
    var tenantId = manywho.utils.extractTenantId(flowKey);
    var cookie = getCookie(tenantId) || null;
    return cookie;
}

var token = queryParameters['authorization'] ? queryParameters['authorization'] : manywho.state.getAuthenticationToken(tenantId);
```


You will also need to add a piece of code just before the call to manywho.engine.initialize to remove duplicated redirect_uris, if you see an error like: OAuth 2 parameters can only have a single value: redirect_uri this will fix that;

`manywho.authorization.invokeAuthorization = function(response, flowKey, onAuthenticated) {

    if (response.authorizationContext != null && response.authorizationContext.directoryId != null) {
        if (manywho.utils.isEqual(response.authorizationContext.authenticationType, 'oauth2', true)) {

            window.location.href = response.authorizationContext.loginUrl.replace(
                'redirect_uri=https%3A%2F%2Fflow.manywho.com%2Fapi%2Frun%2F1%2Foauth2',
                ''
            );

            return;
        }

        if (manywho.utils.isEqual(response.authorizationContext.authenticationType, 'oauth', true)) {
            window.location.href = response.authorizationContext.loginUrl;
            return;
        }

        if (Utils.isEqual(response.authorizationContext.authenticationType, 'saml', true)) {
            window.location.href = response.authorizationContext.loginUrl;
            return;
        }

        manywho.state.setLogin({
            isVisible: true,
            directoryId: response.authorizationContext.directoryId,
            directoryName: response.authorizationContext.directoryName,
            loginUrl: response.authorizationContext.loginUrl,
            stateId: response.stateId,
            callback: onAuthenticated,
        }, flowKey);
    }
}`
